-- Admin Shoe Store schema for PostgreSQL.

DROP TABLE IF EXISTS inventory CASCADE;
DROP TABLE IF EXISTS sold_products CASCADE;
DROP TABLE IF EXISTS product_images CASCADE;
DROP TABLE IF EXISTS product_seasons CASCADE;
DROP TABLE IF EXISTS product_variant CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS inventory_access_requests CASCADE;
DROP TABLE IF EXISTS store_users CASCADE;
DROP TABLE IF EXISTS store CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS colours CASCADE;
DROP TABLE IF EXISTS shoe_type CASCADE;
DROP TABLE IF EXISTS materials CASCADE;
DROP TABLE IF EXISTS brands CASCADE;

DROP TYPE IF EXISTS user_role CASCADE;
DROP TYPE IF EXISTS store_user_role CASCADE;
DROP TYPE IF EXISTS access_request_status CASCADE;
DROP TYPE IF EXISTS product_season CASCADE;
DROP TYPE IF EXISTS shoe_size CASCADE;

CREATE TYPE user_role AS ENUM ('customer', 'seller', 'admin');
CREATE TYPE store_user_role AS ENUM ('owner', 'manager', 'staff');
CREATE TYPE access_request_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE product_season AS ENUM ('spring', 'summer', 'autumn', 'winter', 'all_season');
CREATE TYPE shoe_size AS ENUM ('33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44');

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fname VARCHAR(20) NOT NULL,
    lname VARCHAR(20) NOT NULL,
    telegram_id BIGINT NULL,
    phone_number VARCHAR(15) NOT NULL UNIQUE,
    password_hash CHAR(60) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    role user_role NOT NULL DEFAULT 'customer',

    CONSTRAINT uq_users_telegram_id UNIQUE (telegram_id)
);

CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_phone_number ON users(phone_number);

CREATE TABLE store (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    store_image VARCHAR(500),
    channel_name_telegram VARCHAR(100)
);

CREATE TRIGGER trg_store_updated_at
BEFORE UPDATE ON store
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE INDEX idx_store_is_active ON store(is_active);
CREATE INDEX idx_store_channel_name_telegram ON store(channel_name_telegram);

CREATE TABLE store_users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    store_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    role store_user_role NOT NULL DEFAULT 'owner',

    CONSTRAINT uq_store_users_user_store UNIQUE (user_id, store_id),
    CONSTRAINT fk_store_users_user FOREIGN KEY (user_id) REFERENCES users(id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_store_users_store FOREIGN KEY (store_id) REFERENCES store(id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX idx_store_users_user_id ON store_users(user_id);
CREATE INDEX idx_store_users_store_id ON store_users(store_id);
CREATE INDEX idx_store_users_role ON store_users(role);

CREATE TABLE inventory_access_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_user_id INTEGER NOT NULL,
    store_id INTEGER NOT NULL,
    status access_request_status NOT NULL DEFAULT 'pending',
    requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMP NULL,
    responded_by_user_id INTEGER NULL,

    CONSTRAINT fk_inventory_access_requests_seller FOREIGN KEY (seller_user_id) REFERENCES users(id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_inventory_access_requests_store FOREIGN KEY (store_id) REFERENCES store(id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_inventory_access_requests_responder FOREIGN KEY (responded_by_user_id) REFERENCES users(id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX idx_inventory_access_requests_seller ON inventory_access_requests(seller_user_id);
CREATE INDEX idx_inventory_access_requests_store ON inventory_access_requests(store_id);
CREATE INDEX idx_inventory_access_requests_status ON inventory_access_requests(status);

CREATE TABLE brands (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE materials (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_type VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE shoe_type (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE colours (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    colour_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    art_no VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    brand_id INTEGER NOT NULL,
    type_id INTEGER NOT NULL,
    landing_price NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    price NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_products_brand FOREIGN KEY (brand_id) REFERENCES brands(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_products_type FOREIGN KEY (type_id) REFERENCES shoe_type(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_products_landing_price CHECK (landing_price >= 0),
    CONSTRAINT chk_products_price CHECK (price >= 0)
);

CREATE TRIGGER trg_products_updated_at
BEFORE UPDATE ON products
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE INDEX idx_products_brand_id ON products(brand_id);
CREATE INDEX idx_products_type_id ON products(type_id);
CREATE INDEX idx_products_art_no ON products(art_no);
CREATE INDEX idx_products_name ON products(name);

CREATE TABLE product_seasons (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL,
    season product_season NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_product_seasons_product FOREIGN KEY (product_id) REFERENCES products(id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT uq_product_season UNIQUE (product_id, season)
);

CREATE INDEX idx_product_seasons_product_id ON product_seasons(product_id);
CREATE INDEX idx_product_seasons_season ON product_seasons(season);

CREATE TABLE product_variant (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL,
    colour_id INTEGER NOT NULL,
    material_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_product_variant_product FOREIGN KEY (product_id) REFERENCES products(id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_product_variant_colour FOREIGN KEY (colour_id) REFERENCES colours(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_product_variant_material FOREIGN KEY (material_id) REFERENCES materials(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_product_variant UNIQUE (product_id, colour_id, material_id)
);

CREATE TRIGGER trg_product_variant_updated_at
BEFORE UPDATE ON product_variant
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE INDEX idx_product_variant_product_id ON product_variant(product_id);
CREATE INDEX idx_product_variant_colour_id ON product_variant(colour_id);
CREATE INDEX idx_product_variant_material_id ON product_variant(material_id);

CREATE TABLE product_images (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_variant_id INTEGER NOT NULL,
    image_path VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_product_images_variant FOREIGN KEY (product_variant_id) REFERENCES product_variant(id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX idx_product_images_variant_id ON product_images(product_variant_id);

CREATE TABLE inventory (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_variant_id INTEGER NOT NULL,
    size shoe_size NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    store_id INTEGER NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_inventory_variant FOREIGN KEY (product_variant_id) REFERENCES product_variant(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_inventory_store FOREIGN KEY (store_id) REFERENCES store(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_inventory_variant_size_store UNIQUE (product_variant_id, size, store_id),
    CONSTRAINT chk_inventory_quantity CHECK (quantity >= 0),
    CONSTRAINT chk_inventory_price CHECK (price >= 0)
);

CREATE TRIGGER trg_inventory_updated_at
BEFORE UPDATE ON inventory
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE INDEX idx_inventory_product_variant_id ON inventory(product_variant_id);
CREATE INDEX idx_inventory_store_id ON inventory(store_id);
CREATE INDEX idx_inventory_size ON inventory(size);

CREATE TABLE sold_products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    product_variant_id INTEGER NOT NULL,
    size shoe_size NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    sold_price NUMERIC(10,2) NOT NULL,
    landing_price NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    sold_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sold_products_store FOREIGN KEY (store_id) REFERENCES store(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_sold_products_user FOREIGN KEY (user_id) REFERENCES users(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_sold_products_variant FOREIGN KEY (product_variant_id) REFERENCES product_variant(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_sold_products_quantity CHECK (quantity > 0),
    CONSTRAINT chk_sold_products_price CHECK (sold_price >= 0),
    CONSTRAINT chk_sold_products_landing_price CHECK (landing_price >= 0)
);

CREATE INDEX idx_sold_products_store_id ON sold_products(store_id);
CREATE INDEX idx_sold_products_user_id ON sold_products(user_id);
CREATE INDEX idx_sold_products_product_variant_id ON sold_products(product_variant_id);
CREATE INDEX idx_sold_products_sold_at ON sold_products(sold_at);
