require("dotenv").config();

const { pool, testConnection } = require("./db");

const token = process.env.TELEGRAM_BOT_TOKEN;
const webAppUrl = process.env.TELEGRAM_WEBAPP_URL;
const pollTimeoutSeconds = Number(process.env.TELEGRAM_POLL_TIMEOUT_SECONDS || 25);
const defaultPasswordHash =
  process.env.DEFAULT_OWNER_PASSWORD_HASH || "$2b$10$0000000000000000000000000000000000000000000000000000";
const sessions = new Map();

if (!token) {
  throw new Error("TELEGRAM_BOT_TOKEN is required.");
}

if (!webAppUrl) {
  throw new Error("TELEGRAM_WEBAPP_URL is required.");
}

function cleanText(value) {
  if (value === null || value === undefined) return "";
  return String(value).trim();
}

function normalizePhone(value) {
  const phone = cleanText(value).replace(/\s+/g, "");
  return /^\+?[0-9-]{7,20}$/.test(phone) ? phone : "";
}

function profileFromTelegram(from) {
  return {
    telegramId: Number(from.id),
    telegramUsername: cleanText(from.username),
    telegramFirstName: cleanText(from.first_name),
    telegramLastName: cleanText(from.last_name)
  };
}

async function telegram(method, payload) {
  const response = await fetch(`https://api.telegram.org/bot${token}/${method}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload)
  });
  const data = await response.json();
  if (!data.ok) {
    throw new Error(data.description || `Telegram API ${method} failed.`);
  }
  return data.result;
}

function webAppKeyboard(extraRows = []) {
  return {
    inline_keyboard: [
      [
        {
          text: "Omborni ochish",
          web_app: { url: webAppUrl }
        }
      ],
      ...extraRows
    ]
  };
}

function accountTypeKeyboard() {
  return {
    inline_keyboard: [
      [{ text: "Sotuvchi", callback_data: "account:seller" }],
      [{ text: "Do'kon egasi", callback_data: "account:store_owner" }]
    ]
  };
}

async function sendMessage(chatId, text, replyMarkup) {
  return telegram("sendMessage", {
    chat_id: chatId,
    text,
    reply_markup: replyMarkup
  });
}

async function answerCallbackQuery(callbackQueryId) {
  return telegram("answerCallbackQuery", {
    callback_query_id: callbackQueryId
  });
}

async function ensureInventoryAccessRequestsTable() {
  await pool.execute(
    `CREATE TABLE IF NOT EXISTS inventory_access_requests (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      seller_user_id INTEGER NOT NULL,
      store_id INTEGER NOT NULL,
      status access_request_status NOT NULL DEFAULT 'pending',
      requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      responded_at TIMESTAMP NULL,
      responded_by_user_id INTEGER NULL,

      CONSTRAINT fk_inventory_access_requests_seller
        FOREIGN KEY (seller_user_id) REFERENCES users(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

      CONSTRAINT fk_inventory_access_requests_store
        FOREIGN KEY (store_id) REFERENCES store(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

      CONSTRAINT fk_inventory_access_requests_responder
        FOREIGN KEY (responded_by_user_id) REFERENCES users(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
    )`
  );

  const indexes = [
    ["idx_inventory_access_requests_seller", "seller_user_id"],
    ["idx_inventory_access_requests_store", "store_id"],
    ["idx_inventory_access_requests_status", "status"]
  ];

  for (const [indexName, columnName] of indexes) {
    const [existing] = await pool.execute(
      `SELECT 1
       FROM pg_indexes
       WHERE schemaname = 'public'
         AND tablename = 'inventory_access_requests'
         AND indexname = ?
       LIMIT 1`,
      [indexName]
    );

    if (!existing.length) {
      await pool.query(`CREATE INDEX IF NOT EXISTS "${indexName}" ON inventory_access_requests("${columnName}")`);
    }
  }
}

async function findUserByTelegramId(telegramId) {
  const [users] = await pool.execute(
    `SELECT
       u.id,
       u.fname,
      u.lname,
      u.phone_number AS phoneNumber,
      u.role,
       s.store_name AS storeName,
       su.role AS storeRole
     FROM users u
     LEFT JOIN store_users su ON su.user_id = u.id
     LEFT JOIN store s ON s.id = su.store_id AND s.is_active = TRUE
     WHERE u.telegram_id = ?
     ORDER BY CASE su.role WHEN 'owner' THEN 1 WHEN 'manager' THEN 2 WHEN 'staff' THEN 3 ELSE 4 END, s.id
     LIMIT 1`,
    [telegramId]
  );
  return users[0] || null;
}

async function findUserById(userId) {
  const [users] = await pool.execute(
    `SELECT
       id,
       fname,
       lname,
       phone_number AS phoneNumber,
       telegram_id AS telegramId,
       role
     FROM users
     WHERE id = ?
     LIMIT 1`,
    [userId]
  );
  return users[0] || null;
}

async function findStoreOwnerByStoreName(storeName) {
  const [owners] = await pool.execute(
    `SELECT
       s.id AS storeId,
       s.store_name AS storeName,
       u.id AS ownerUserId,
       u.telegram_id AS ownerTelegramId
     FROM store s
     INNER JOIN store_users su ON su.store_id = s.id AND su.role = 'owner'
     INNER JOIN users u ON u.id = su.user_id
     WHERE LOWER(s.store_name) = LOWER(?)
       AND s.is_active = TRUE
       AND u.telegram_id IS NOT NULL
     ORDER BY su.created_at ASC, su.id ASC
     LIMIT 1`,
    [storeName]
  );
  return owners[0] || null;
}

async function requestInventoryAccess(chatId, sellerUserId, storeName) {
  const storeOwner = await findStoreOwnerByStoreName(storeName);
  if (!storeOwner) {
    await sendMessage(chatId, "Do'kon topilmadi yoki egasi Telegram bilan bog'lanmagan. Do'kon nomini tekshiring.");
    return false;
  }

  const [memberships] = await pool.execute(
    "SELECT id FROM store_users WHERE user_id = ? AND store_id = ? LIMIT 1",
    [sellerUserId, storeOwner.storeId]
  );
  if (memberships.length) {
    await sendMessage(chatId, `${storeOwner.storeName} omboriga sizda allaqachon ruxsat bor.`, webAppKeyboard());
    return true;
  }

  const [pendingRequests] = await pool.execute(
    `SELECT id
     FROM inventory_access_requests
     WHERE seller_user_id = ?
       AND store_id = ?
       AND status = 'pending'
     ORDER BY requested_at DESC
     LIMIT 1`,
    [sellerUserId, storeOwner.storeId]
  );

  const requestId = pendingRequests[0]?.id || (await pool.execute(
    `INSERT INTO inventory_access_requests (seller_user_id, store_id, status)
     VALUES (?, ?, 'pending')`,
    [sellerUserId, storeOwner.storeId]
  ))[0].insertId;

  const seller = await findUserById(sellerUserId);
  await sendMessage(
    storeOwner.ownerTelegramId,
    `Omborga kirish so'rovi\n\nDo'kon: ${storeOwner.storeName}\nSotuvchi: ${seller.fname} ${seller.lname}\nTelefon: ${seller.phoneNumber}`,
    {
      inline_keyboard: [
        [
          { text: "Qabul qilish", callback_data: `access:approve:${requestId}` },
          { text: "Rad etish", callback_data: `access:reject:${requestId}` }
        ]
      ]
    }
  );

  await sendMessage(chatId, `So'rovingiz ${storeOwner.storeName} egasiga yuborildi. Tasdiqlangandan keyin omborga kira olasiz.`);
  return true;
}

async function respondToInventoryAccessRequest(callbackQuery, action, requestId) {
  const owner = await findUserByTelegramId(callbackQuery.from.id);
  if (!owner) {
    await sendMessage(callbackQuery.message.chat.id, "Do'kon egasi akkaunti topilmadi. Avval /start yuboring.");
    return;
  }

  const connection = await pool.getConnection();
  try {
    await connection.beginTransaction();

    const [requests] = await connection.execute(
      `SELECT
         iar.id,
         iar.seller_user_id AS sellerUserId,
         iar.store_id AS storeId,
         iar.status,
         s.store_name AS storeName,
         u.telegram_id AS sellerTelegramId
       FROM inventory_access_requests iar
       INNER JOIN store s ON s.id = iar.store_id
       INNER JOIN users u ON u.id = iar.seller_user_id
       INNER JOIN store_users owner_su
         ON owner_su.store_id = iar.store_id
        AND owner_su.user_id = ?
        AND owner_su.role = 'owner'
       WHERE iar.id = ?
       LIMIT 1
       FOR UPDATE`,
      [owner.id, requestId]
    );

    const accessRequest = requests[0];
    if (!accessRequest) {
      await connection.rollback();
      await sendMessage(callbackQuery.message.chat.id, "Bu so'rov topilmadi yoki sizning do'koningizga tegishli emas.");
      return;
    }

    if (accessRequest.status !== "pending") {
      await connection.rollback();
      await sendMessage(callbackQuery.message.chat.id, `Bu so'rov allaqachon ${accessRequest.status}.`);
      return;
    }

    const status = action === "approve" ? "approved" : "rejected";
    await connection.execute(
      `UPDATE inventory_access_requests
       SET status = ?, responded_at = NOW(), responded_by_user_id = ?
       WHERE id = ?`,
      [status, owner.id, requestId]
    );

    if (status === "approved") {
      await connection.execute(
        `INSERT INTO store_users (user_id, store_id, role)
         VALUES (?, ?, 'staff')
         ON CONFLICT (user_id, store_id) DO UPDATE SET role = EXCLUDED.role`,
        [accessRequest.sellerUserId, accessRequest.storeId]
      );
    }

    await connection.commit();

    await sendMessage(
      callbackQuery.message.chat.id,
      status === "approved"
        ? `${accessRequest.storeName} uchun ruxsat tasdiqlandi.`
        : `${accessRequest.storeName} uchun ruxsat rad etildi.`
    );

    if (accessRequest.sellerTelegramId) {
      await sendMessage(
        accessRequest.sellerTelegramId,
        status === "approved"
          ? `${accessRequest.storeName} omboriga kirish ruxsatingiz tasdiqlandi. Kelish narxi va egaga tegishli maydonlar sizdan yashiriladi.`
          : `${accessRequest.storeName} uchun kirish so'rovingiz rad etildi.`,
        status === "approved" ? webAppKeyboard() : undefined
      );
    }
  } catch (error) {
    await connection.rollback();
    throw error;
  } finally {
    connection.release();
  }
}

async function createTelegramUser(profile, data) {
  const connection = await pool.getConnection();

  try {
    await connection.beginTransaction();

    const [existingByPhone] = await connection.execute(
      "SELECT id, telegram_id AS telegramId FROM users WHERE phone_number = ? LIMIT 1",
      [data.phoneNumber]
    );

    if (existingByPhone.length) {
      const existingUser = existingByPhone[0];
      if (existingUser.telegramId && Number(existingUser.telegramId) !== profile.telegramId) {
        throw new Error("Bu telefon raqami boshqa Telegram akkauntiga ulangan.");
      }

      await connection.execute(
        `UPDATE users
         SET telegram_id = ?,
             role = CASE WHEN role IN ('customer', 'seller') THEN ? ELSE role END
         WHERE id = ?`,
        [
          profile.telegramId,
          data.userRole,
          existingUser.id
        ]
      );

      let storeId = null;
      if (data.storeRole === "owner") {
        const [stores] = await connection.execute(
          `SELECT s.id
           FROM store_users su
           INNER JOIN store s ON s.id = su.store_id
           WHERE su.user_id = ? AND su.role = 'owner'
           ORDER BY s.id
           LIMIT 1`,
          [existingUser.id]
        );
        storeId = stores[0]?.id || null;

        if (!storeId) {
          const [storeInsert] = await connection.execute(
            `INSERT INTO store (store_name, is_active, channel_name_telegram)
             VALUES (?, TRUE, ?)`,
            [data.storeName, profile.telegramUsername || null]
          );
          storeId = storeInsert.insertId;
        }

        await connection.execute(
          `INSERT INTO store_users (user_id, store_id, role)
           VALUES (?, ?, 'owner')
           ON CONFLICT (user_id, store_id) DO NOTHING`,
          [existingUser.id, storeId]
        );
      }

      await connection.commit();
      return { userId: existingUser.id, storeId };
    }

    const [userInsert] = await connection.execute(
      `INSERT INTO users (
         fname,
         lname,
         phone_number,
         password_hash,
         telegram_id,
         role
       )
       VALUES (?, ?, ?, ?, ?, ?)`,
      [
        data.firstName,
        data.lastName,
        data.phoneNumber,
        defaultPasswordHash,
        profile.telegramId,
        data.userRole
      ]
    );

    let storeId = null;
    if (data.storeRole === "owner") {
      const [storeInsert] = await connection.execute(
        `INSERT INTO store (store_name, is_active, channel_name_telegram)
         VALUES (?, TRUE, ?)`,
        [data.storeName, profile.telegramUsername || null]
      );
      storeId = storeInsert.insertId;

      await connection.execute(
        `INSERT INTO store_users (user_id, store_id, role)
         VALUES (?, ?, 'owner')`,
        [userInsert.insertId, storeId]
      );
    }

    await connection.commit();
    return { userId: userInsert.insertId, storeId };
  } catch (error) {
    await connection.rollback();
    throw error;
  } finally {
    connection.release();
  }
}

async function showStart(chatId, from) {
  const profile = profileFromTelegram(from);
  const user = await findUserByTelegramId(profile.telegramId);

  if (user) {
    await sendMessage(chatId, "Qaytganingiz bilan.", webAppKeyboard([
      [{ text: "Profil", callback_data: "profile" }],
      [{ text: "Yordam", callback_data: "help" }]
    ]));
    return;
  }

  sessions.set(chatId, {
    step: "first_name",
    profile,
    data: {}
  });
  await sendMessage(chatId, "Oyoq kiyim omboriga xush kelibsiz.\n\nDo'kon omborini Telegram orqali boshqaring.", webAppKeyboard());
  await sendMessage(chatId, "Xush kelibsiz!\n\nKeling, akkauntingizni yaratamiz.\n\nIsmingizni yuboring.");
}

async function handleContact(chatId, from, contact) {
  const session = sessions.get(chatId);
  if (!session || session.step !== "phone") return;

  if (Number(contact.user_id) !== Number(from.id)) {
    await sendMessage(chatId, "Iltimos, o'zingizning Telegram akkauntingiz uchun Telefon raqamni ulashish tugmasidan foydalaning.");
    return;
  }

  const phoneNumber = normalizePhone(contact.phone_number);
  if (!phoneNumber) {
    await sendMessage(chatId, "Telefon raqami formati noto'g'ri. Qayta urinib ko'ring.");
    return;
  }

  session.data.phoneNumber = phoneNumber.startsWith("+") ? phoneNumber : `+${phoneNumber}`;
  session.step = "account_type";
  sessions.set(chatId, session);

  await sendMessage(chatId, "Akkaunt turini tanlang:", accountTypeKeyboard());
}

async function handleRegistrationText(chatId, text) {
  const session = sessions.get(chatId);
  if (!session) return false;

  if (session.step === "first_name") {
    const firstName = cleanText(text);
    if (!firstName || firstName.length > 20) {
      await sendMessage(chatId, "Ism 20 ta belgidan oshmasin.");
      return true;
    }
    session.data.firstName = firstName;
    session.step = "last_name";
    sessions.set(chatId, session);
    await sendMessage(chatId, "Familiyangizni yuboring.");
    return true;
  }

  if (session.step === "last_name") {
    const lastName = cleanText(text);
    if (!lastName || lastName.length > 20) {
      await sendMessage(chatId, "Familiya 20 ta belgidan oshmasin.");
      return true;
    }
    session.data.lastName = lastName;
    session.step = "phone";
    sessions.set(chatId, session);
    await sendMessage(chatId, "Telefon raqamingizni ulashing.", {
      keyboard: [[{ text: "Telefon raqamni ulashish", request_contact: true }]],
      resize_keyboard: true,
      one_time_keyboard: true
    });
    return true;
  }

  if (session.step === "store_name") {
    const storeName = cleanText(text);
    if (!storeName || storeName.length > 50) {
      await sendMessage(chatId, "Do'kon nomi 1-50 ta belgi bo'lishi kerak.");
      return true;
    }
    session.data.storeName = storeName;
    await finishRegistration(chatId, session);
    return true;
  }

  if (session.step === "seller_store_name") {
    const storeName = cleanText(text);
    if (!storeName || storeName.length > 50) {
      await sendMessage(chatId, "Do'kon nomi 1-50 ta belgi bo'lishi kerak.");
      return true;
    }

    const requested = await requestInventoryAccess(chatId, session.userId, storeName);
    if (requested) {
      sessions.delete(chatId);
    }
    return true;
  }

  return true;
}

async function finishRegistration(chatId, session) {
  await createTelegramUser(session.profile, session.data);
  sessions.delete(chatId);
  await sendMessage(chatId, "Akkaunt yaratildi. Endi ombor panelini ochishingiz mumkin.", webAppKeyboard());
}

async function handleCallback(callbackQuery) {
  const chatId = callbackQuery.message.chat.id;
  const data = callbackQuery.data;
  await answerCallbackQuery(callbackQuery.id);

  if (data === "profile") {
    const user = await findUserByTelegramId(callbackQuery.from.id);
    await sendMessage(
      chatId,
      user
        ? `Profil\n\nIsm: ${user.fname} ${user.lname}\nRol: ${user.role}\nDo'kon: ${user.storeName || "Biriktirilmagan"}`
        : "Profil topilmadi. /start yuboring."
    );
    return;
  }

  if (data === "help") {
    await sendMessage(chatId, "Telegram ichida ombor panelini ochish uchun Omborni ochish tugmasini bosing.");
    return;
  }

  if (data.startsWith("access:")) {
    const [, action, requestIdText] = data.split(":");
    const requestId = Number(requestIdText);
    if (!["approve", "reject"].includes(action) || !Number.isInteger(requestId) || requestId <= 0) {
      await sendMessage(chatId, "Kirish so'rovi amali noto'g'ri.");
      return;
    }
    await respondToInventoryAccessRequest(callbackQuery, action, requestId);
    return;
  }

  if (!data.startsWith("account:")) return;

  const session = sessions.get(chatId);
  if (!session || session.step !== "account_type") {
    await sendMessage(chatId, "Ro'yxatdan o'tishni boshlash uchun /start yuboring.");
    return;
  }

  const accountType = data.slice("account:".length);
  if (!["seller", "store_owner"].includes(accountType)) {
    await sendMessage(chatId, "Sotuvchi yoki Do'kon egasini tanlang.");
    return;
  }

  session.data.userRole = "seller";
  session.data.storeRole = accountType === "store_owner" ? "owner" : null;
  if (accountType === "store_owner") {
    session.step = "store_name";
    sessions.set(chatId, session);
    await sendMessage(chatId, "Do'kon nomini yuboring.");
    return;
  }

  const created = await createTelegramUser(session.profile, session.data);
  session.userId = created.userId;
  session.step = "seller_store_name";
  sessions.set(chatId, session);
  await sendMessage(chatId, "Akkaunt yaratildi. Omborga kirish so'rovini yuborish uchun do'kon nomini kiriting.");
}

async function handleUpdate(update) {
  if (update.callback_query) {
    await handleCallback(update.callback_query);
    return;
  }

  const message = update.message;
  if (!message?.chat || !message.from) return;

  const chatId = message.chat.id;
  if (message.text === "/start") {
    await showStart(chatId, message.from);
    return;
  }

  if (message.contact) {
    await handleContact(chatId, message.from, message.contact);
    return;
  }

  if (message.text && (await handleRegistrationText(chatId, message.text))) {
    return;
  }

  await sendMessage(chatId, "Ombor imkoniyatlarini ochish uchun /start yuboring.");
}

async function startBot() {
  await testConnection();
  await ensureInventoryAccessRequestsTable();
  let offset = 0;
  console.log("Telegram inventory bot is running.");

  while (true) {
    try {
      const updates = await telegram("getUpdates", {
        offset,
        timeout: pollTimeoutSeconds,
        allowed_updates: ["message", "callback_query"]
      });

      for (const update of updates) {
        offset = update.update_id + 1;
        await handleUpdate(update);
      }
    } catch (error) {
      console.error(`Telegram bot error: ${error.message}`);
      await new Promise((resolve) => setTimeout(resolve, 3000));
    }
  }
}

startBot().catch((error) => {
  console.error(error);
  process.exit(1);
});
